### ISSUE TITLE
F4SE build: 0.6.17 supports Fallout 4 runtime 1.10.138

### ISSUE THREAD

**Issue by Scrivener07** [osvein/f4se-mirror#1]
New F4SE build: 0.6.17 supports Fallout 4 runtime 1.10.138
https://f4se.silverlock.org/

**Comment by reg2k** [comment]
Updated: https://github.com/osvein/f4se-mirror/tree/v0.6.17

**Comment by Scrivener07** [comment]
Thanks for doing the dirty work reg2k!

**Comment by ElementalSon** [comment]
Hey guys - thanks again for all your hard work. I am having an error, where my Fallout 4 runtime 1.10.138 apparently is newer than the F4SE build 0.6.17 and won't run. This issue is through Mod Organizer 2, auto-sorted by LOOT. 

The full error reads:

```
Your Fallout 4 is up-to-date.

It appears you do not have the latest version of Script Extender (F4SE). Some mods may require functionality added in the latest version of Script Extender (F4SE) to work.

Your installed version of Script Extender (F4SE) is not compatible with your version of Fallout 4.
```

Any advice? Thanks again.

**Comment by mushiiig** [comment]
Here is Another Official Announcement for Fallout 4 script extender 
http://scriptextender.com/
